version: '1'
services:
  node-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
    environment:
      - NODE_ENV=development
    command: npm run start:dev